#ifndef QPADISSECTOR_GLOBAL_H
#define QPADISSECTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPADISSECTOR_LIBRARY)
#  define QPADISSECTORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPADISSECTORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPADISSECTOR_GLOBAL_H
