#ifndef QPRFACCESSOR_GLOBAL_H
#define QPRFACCESSOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPRFACCESSOR_LIBRARY)
#  define QPRFACCESSORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPRFACCESSORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPRFACCESSOR_GLOBAL_H
