#ifndef QPADISSECTORSUTIL_GLOBAL_H
#define QPADISSECTORSUTIL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPADISSECTORSUTIL_LIBRARY)
#  define QPADISSECTORSUTILSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPADISSECTORSUTILSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPADISSECTORSUTIL_GLOBAL_H
