#ifndef QPAFIELDTYPE_GLOBAL_H
#define QPAFIELDTYPE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPAFIELDTYPE_LIBRARY)
#  define QPAFIELDTYPESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPAFIELDTYPESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPAFIELDTYPE_GLOBAL_H
