#ifndef QPAUTILIZATION_GLOBAL_H
#define QPAUTILIZATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPAUTILIZATION_LIBRARY)
#  define QPAUTILIZATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPAUTILIZATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPAUTILIZATION_GLOBAL_H
